# Generated by Django 4.2.3 on 2023-07-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_subtitlefiles_video_created_at_video_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
    ]
