# Generated by Django 4.2.3 on 2023-07-14 11:12

from django.db import migrations, models
import videoapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_language_subtitlefiles_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitlefiles',
            name='subtitle',
            field=models.FileField(upload_to='subtitles/', validators=[videoapp.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[videoapp.validators.validate_file_extension]),
        ),
    ]
