# Generated by Django 4.2.3 on 2023-07-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0006_filter_video_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='filters',
        ),
    ]
