# Generated by Django 4.2.3 on 2023-07-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0007_remove_video_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtered_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered_video', models.FileField(upload_to='modified_videos/')),
                ('applied_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_apply', to='videoapp.filter')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_video', to='videoapp.video')),
            ],
            options={
                'unique_together': {('applied_filter', 'video')},
            },
        ),
    ]
